import type { Plugin } from "@opencode-ai/plugin"
import { appendFileSync, mkdirSync, existsSync, writeFileSync } from "fs"
import { join } from "path"

/**
 * Interaction Archiver Plugin for OpenCode
 *
 * Automatically archives all user prompts, assistant responses, and plan/todo
 * updates to a structured directory under .opencode-archive/YYYY/MM/.
 *
 * Archive structure:
 *   .opencode-archive/YYYY/MM/
 *     day_01_to_10/
 *       prompts.log          - JSONL append-only machine-readable log
 *       prompt_and_plan.md   - Chronological human-readable markdown
 *     day_11_to_20/
 *       ...
 *     day_21_to_31/
 *       ...
 */

interface ArchivePaths {
  bucketDir: string
  logPath: string
  mdPath: string
}

export const InteractionArchiver: Plugin = async ({ directory }) => {
  const archiveRoot = join(directory, ".opencode-archive")

  if (!existsSync(archiveRoot)) {
    mkdirSync(archiveRoot, { recursive: true })
  }

  function getBucketPath(date: Date): ArchivePaths {
    const year = date.getFullYear().toString()
    const month = (date.getMonth() + 1).toString().padStart(2, "0")
    const day = date.getDate()

    let bucket: string
    if (day <= 10) bucket = "day_01_to_10"
    else if (day <= 20) bucket = "day_11_to_20"
    else bucket = "day_21_to_31"

    const bucketDir = join(archiveRoot, year, month, bucket)
    mkdirSync(bucketDir, { recursive: true })

    return {
      bucketDir,
      logPath: join(bucketDir, "prompts.log"),
      mdPath: join(bucketDir, "prompt_and_plan.md"),
    }
  }

  function appendLog(entry: Record<string, unknown>): void {
    const { logPath } = getBucketPath(new Date())
    appendFileSync(logPath, JSON.stringify(entry) + "\n", "utf-8")
  }

  function appendMarkdown(title: string, content: string): void {
    const { mdPath } = getBucketPath(new Date())
    const timestamp = new Date().toISOString()

    if (!existsSync(mdPath)) {
      writeFileSync(
        mdPath,
        "# Interaction Archive\n\nGenerated by OpenCode Interaction Archiver Plugin\n\n---\n",
        "utf-8"
      )
    }

    const entry = `\n## ${title}\n\n**Timestamp:** ${timestamp}\n\n${content}\n\n---\n`
    appendFileSync(mdPath, entry, "utf-8")
  }

  function extractText(parts: Array<{ type: string; text?: string }>): string {
    return parts
      .filter((p): p is { type: "text"; text: string } => p.type === "text" && p.text !== undefined)
      .map((p) => p.text)
      .join("")
  }

  // Capture user prompts
  const chatMessage = async (
    input: { sessionID: string; agent?: string; messageID?: string },
    output: { parts: Array<{ type: string; text?: string }> }
  ) => {
    const text = extractText(output.parts)

    appendLog({
      event: "user_prompt",
      timestamp: new Date().toISOString(),
      sessionID: input.sessionID,
      agent: input.agent ?? "unknown",
      messageID: input.messageID ?? "unknown",
      prompt: text,
    })

    appendMarkdown(
      `User Prompt \u2014 Agent: ${input.agent ?? "unknown"}`,
      [
        `**Session ID:** \`${input.sessionID}\``,
        `**Message ID:** \`${input.messageID ?? "unknown"}\``,
        "",
        "### Prompt",
        "",
        text || "_(empty)_",
      ].join("\n")
    )
  }

  // Capture session lifecycle and assistant responses
  const eventHandler = async ({ event }: { event: { type: string; properties?: Record<string, unknown> } }) => {
    const ts = new Date().toISOString()

    switch (event.type) {
      // Session lifecycle
      case "session.created": {
        appendLog({
          event: "session_created",
          timestamp: ts,
          properties: event.properties,
        })
        appendMarkdown(
          "Session Created",
          `**Properties:**\n\n\`\`\`json\n${JSON.stringify(event.properties, null, 2)}\n\`\`\``
        )
        break
      }

      case "session.idle": {
        appendLog({
          event: "session_idle",
          timestamp: ts,
          properties: event.properties,
        })
        break
      }

      case "session.error": {
        appendLog({
          event: "session_error",
          timestamp: ts,
          properties: event.properties,
        })
        appendMarkdown(
          "Session Error",
          `**Properties:**\n\n\`\`\`json\n${JSON.stringify(event.properties, null, 2)}\n\`\`\``
        )
        break
      }

      // Todo / plan updates
      case "todo.updated": {
        const props = event.properties as Record<string, unknown> | undefined
        appendLog({
          event: "todo_updated",
          timestamp: ts,
          properties: props,
        })
        appendMarkdown(
          "Todo / Plan Updated",
          `**Properties:**\n\n\`\`\`json\n${JSON.stringify(props, null, 2)}\n\`\`\``
        )
        break
      }

      // Assistant responses
      case "message.updated": {
        const props = event.properties as Record<string, unknown> | undefined
        const msg = props?.message as Record<string, unknown> | undefined
        if (msg && msg.role === "assistant") {
          const content = typeof msg.content === "string" ? msg.content : JSON.stringify(msg.content ?? "")
          const sessionID = typeof props?.sessionID === "string" ? props.sessionID : "unknown"
          const messageID = typeof msg.id === "string" ? msg.id : "unknown"

          appendLog({
            event: "assistant_response",
            timestamp: ts,
            sessionID,
            messageID,
            content,
          })

          appendMarkdown(
            "Assistant Response",
            [
              `**Session ID:** \`${sessionID}\``,
              `**Message ID:** \`${messageID}\``,
              "",
              "### Response",
              "",
              content || "_(empty)_",
            ].join("\n")
          )
        }
        break
      }

      // Ignore all other events
      default:
        break
    }
  }

  console.log("[interaction-archiver] Plugin loaded. Archiving to .opencode-archive/")

  return {
    "chat.message": chatMessage,
    event: eventHandler,
  }
}
